### ISSUE TITLE
I need to hire a person for a job on this project, basically installation.

### ISSUE THREAD

**Issue by salsavalencia2000** [bchah/ontario-covid#1]
Hello, my name is Juan José, I am from Spain.
I saw that you have some references to the project:
https://airensoft.gitbook.io/ovenmediaengine

I need to hire a person for a job on this project, basically installation.
my email :
trabajoweb2015@hotmail.com

My Skype is :
juanjose__2014

**Comment by bchah** [comment]
Hi, this is an issue thread for an unrelated, mostly dead repo. Please DM if serious.
